name: bluedot_point_sdk_push
description: >
  Optional push notifications module for the Bluedot Point SDK Flutter plugin.
  Adds APNs and Firebase Cloud Messaging support via PointSDK.
version: 2.2.0
homepage: "https://bluedot.io"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bluedot_point_sdk: ^2.2.0

flutter:
  plugin:
    platforms:
      android:
        package: io.bluedot.pushnotifications
        pluginClass: BluedotPushPlugin
      ios:
        pluginClass: BluedotPointSdkPushPlugin
