group 'io.bluedot.bluedot_point_sdk'
version '2.1.2'

buildscript {
    ext.kotlin_version = '2.3.0'
    ext.sdk_version = '17.4.1'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {

    namespace 'io.bluedot.bluedot_point_sdk'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 29
        compileSdk 36
    }
}

dependencies {
    implementation "com.gitlab.bluedotio.android:point_sdk_android:$sdk_version"

    //NOTE: This is used when building with MavenLocal.
    //implementation "com.github.Bluedot-Innovation:pointsdk:1262"
}
